Web/Controllers/ContactoController.cs
using Core.Interfaces;
using Core.Services;
using Infraestructure.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Web.Utils;

namespace Web.Controllers
{
    public class ContactoController : Controller
    {
        // GET: Contacto
        public ActionResult Index()
        {
            IServiceContacto _ServiceContacto = new ServiceContacto();
            IEnumerable<Contacto> contactos = _ServiceContacto.GetContactos();
            return View(contactos);
        }

        // GET: Contacto/Details/5
        public ActionResult Details(int? id)
        {
            IServiceContacto _ServiceContacto = new ServiceContacto();
            Contacto contacto;
            try
            {
                if (id == null)
                {
                    return RedirectToAction("Index");
                }

                contacto = _ServiceContacto.GetContactoById(id.Value);

                if (contacto == null)
                {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                return RedirectToAction("Index");
            }
            return View(contacto);
        }





        
        public ActionResult Create()
        {
            return View();
        }

        // POST: Contacto/Create
        [HttpPost]
        public ActionResult Save(Contacto contacto)
        {
            IServiceContacto _ServiceContacto = new ServiceContacto();
            try
            {
                Contacto oContacto = _ServiceContacto.Save(contacto);

                return RedirectToAction("Index");
            }
            catch
            {
                Utils.Utils.ValidateErrors(this);
                return View("Create", contacto);
            }
        }

        // GET: Contacto/Edit/5
        public ActionResult Edit(int? id)
        {
            IServiceContacto _ServiceContacto = new ServiceContacto();
            Contacto contacto;
            try
            {
                if (id == null)
                {
                    return RedirectToAction("Index");
                }

                contacto = _ServiceContacto.GetContactoById(id.Value);

                if (contacto == null)
                {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                return RedirectToAction("Index");
            }
            return View(contacto);
        }

       

        // GET: Contacto/Delete/5
        public ActionResult Delete(int? id)
        {
            IServiceContacto _ServiceContacto = new ServiceContacto();
            Contacto contacto;
            try
            {
                if (id == null)
                {
                    return RedirectToAction("Index");
                }

                contacto = _ServiceContacto.GetContactoById(id.Value);

                if (contacto == null)
                {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                return RedirectToAction("Index");
            }
            return View(contacto);
        }

        // POST: Contacto/Delete/5
        [HttpPost]
        public ActionResult DeleteContacto(Contacto contacto)
        {
            IServiceContacto _ServiceContacto = new ServiceContacto();
            Contacto oContacto;
            try
            {
                oContacto = _ServiceContacto.GetContactoById(contacto.Id);
                if (oContacto.Proveedor.Count() > 0)
                {
                    return ViewBag.NotificationMessage = SweetAlerts.Mensaje("Error", "No puede eliminar un contacto asignado a un proveedor ", SweetAlerts.SweetAlertMessageType.error);
                }
                else
                {
                    _ServiceContacto.DeleteContacto(contacto.Id);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                Utils.Utils.ValidateErrors(this);
                return View("Delete", _ServiceContacto.GetContactoById(contacto.Id));
            }
            
        }
    }
}

Web/Views/Contacto/Create.cshtml
@model Infraestructure.Models.Contacto

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<h2>Crear</h2>


@using (Html.BeginForm("Save", "Contacto", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Contacto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.Correo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Atrás", "Index", null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web/Views/Contacto/Delete.cshtml
@model Infraestructure.Models.Contacto

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<h2>Delete</h2>

<h3>Quieres eliminarlo?</h3>
<div>
    <h4>Contacto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Correo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Correo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

    </dl>
    <br />

    @using (Html.BeginForm("DeleteContacto", "Contacto", new { Id = Model.Id, FormMethod.Post }))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-primary" /> |
            @Html.ActionLink("Atrás", "Index", null, new { @class = "btn btn-primary" })
        </div>
    }
</div>

Web/Views/Contacto/Details.cshtml
@model Infraestructure.Models.Contacto

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<h2>Detalles</h2>

<div>
    <h4>Contacto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Correo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Correo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Atrás", "Index",null, new { @class = "btn btn-primary" })
</p>

Web/Views/Contacto/Edit.cshtml
@model Infraestructure.Models.Contacto

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<h2>Editar</h2>


@using (Html.BeginForm("Save", "Contacto", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Contacto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.Correo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>
        <br/>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Atrás", "Index", null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web/Views/Contacto/Index.cshtml
@model IEnumerable<Infraestructure.Models.Contacto>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<h2>Contactos</h2>


<div class="d-grid gap-2 d-md-block">
    <a href="@Url.Action("Create","Contacto")" class="btn btn-primary">Crear nuevo contacto</a>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Correo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefono)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Correo)
        </td>
        <td>
           (+506) @Html.DisplayFor(modelItem => item.Telefono)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }, new { @class = "btn btn-primary" }) |
            @Html.ActionLink("Detalles", "Details", new { id=item.Id }, new { @class = "btn btn-secondary" }) |
            @Html.ActionLink("Eliminar", "Delete", new { id=item.Id }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>