Web/Controllers/UsuarioController.cs
using Core.Interfaces;
using Core.Services;
using Infraestructure.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Web.Utils;

namespace Web.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        public ActionResult Index()
        {
            IServiceUsuario _ServiceUsuario = new ServiceUsuario();
            IEnumerable<Usuario> usuarios = _ServiceUsuario.GetUsuarios();
            return View(usuarios);
        }

        
        public ActionResult Details(int? id)
        {
            IServiceUsuario _ServiceUsuario = new ServiceUsuario();
            Usuario usuario;
            try
            {
                if (id == null)
                {
                    return RedirectToAction("Index");
                }

                usuario = _ServiceUsuario.GetUsuarioById(id.Value);

                if (usuario == null)
                {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                return RedirectToAction("Index");
            }
            return View(usuario);
        }

       
        public ActionResult Edit(int? id)
        {
            IServiceUsuario _ServiceUsuario = new ServiceUsuario();
            Usuario usuario;
            try
            {
                if (id == null)
                {
                    return RedirectToAction("Index");
                }

                usuario = _ServiceUsuario.GetUsuarioById(id.Value);

                if (usuario == null)
                {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                return RedirectToAction("Index");
            }
            return View(usuario);
        }

        public ActionResult Delete(int? id)
        {
            IServiceUsuario _ServiceUsuario = new ServiceUsuario();
            Usuario usuario;
            try
            {
                if (id == null)
                {
                    return RedirectToAction("Index");
                }

                usuario = _ServiceUsuario.GetUsuarioById(id.Value);

                if (usuario == null)
                {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                return RedirectToAction("Index");
            }
            return View(usuario);
        }


        [HttpPost]
        public ActionResult UpdateUsuario(Usuario usuario)
        {
            IServiceUsuario _ServiceUsuario = new ServiceUsuario();
            try
            {
                _ServiceUsuario.EditarRolUsuario(usuario.Id);
                ViewBag.NotificationMessage = SweetAlerts.Mensaje("Success", "Usuario editado", SweetAlerts.SweetAlertMessageType.success);
            }
            catch
            {

                Utils.Utils.ValidateErrors(this);
                return View("Delete", _ServiceUsuario.GetUsuarioById(usuario.Id));
            }

            return RedirectToAction("Index");
        }


        public ActionResult Suspender(int? id)
        {
            IServiceUsuario _ServiceUsuario = new ServiceUsuario();
            Usuario usuario;
            try
            {
                if (id == null)
                {
                    return RedirectToAction("Index");
                }

                usuario = _ServiceUsuario.GetUsuarioById(id.Value);

                if (usuario == null)
                {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                return RedirectToAction("Index");
            }
            return View(usuario);
        }

        public ActionResult SuspenderUsuario(Usuario usuario)
        {
            IServiceUsuario _ServiceUsuario = new ServiceUsuario();
            try
            {
                _ServiceUsuario.SuspenderRolUsuario(usuario.Id);
                ViewBag.NotificationMessage = SweetAlerts.Mensaje("Success", "Usuario editado", SweetAlerts.SweetAlertMessageType.success);
            }
            catch
            {

                Utils.Utils.ValidateErrors(this);
                return View("Delete", _ServiceUsuario.GetUsuarioById(usuario.Id));
            }

            return RedirectToAction("Index");
        }


        [HttpPost]
        public ActionResult DeleteUsuario(Usuario usuario)
        {
            IServiceUsuario _ServiceUsuario = new ServiceUsuario();
            Usuario oUsuario;

            try
            {
                oUsuario = _ServiceUsuario.GetUsuarioById(usuario.Id);
                if (oUsuario.Movimientos.Count() == 0)
                {
                    _ServiceUsuario.DeleteUsuario(usuario.Id);
                }
                else
                {
                    return ViewBag.NotificationMessage = SweetAlerts.Mensaje("Error", "No puede al usuario debido a que tiene movimientos enlazados", SweetAlerts.SweetAlertMessageType.error);
                }
            }
            catch
            {

                Utils.Utils.ValidateErrors(this);
                return View("Delete", _ServiceUsuario.GetUsuarioById(usuario.Id));
            }

            return RedirectToAction("Index");
        }
    }
}

Web/Views/Usuario/Delete.cshtml
@model Infraestructure.Models.Usuario

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}



<h3>Quieres eliminarlo?</h3>
<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ubicacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ubicacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Correo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Correo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>

        <dd>
            @if (Model.Tipo == 0)
            {
                <span> Sin Rol</span>
            }
            else if (Model.Tipo == 1)
            {
                <span>Administrador</span>
            }
            else
            {
                <span>
                    Encargado
                </span>
            }
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteUsuario", "Usuario", new { Id = Model.Id, FormMethod.Post }))
    { 
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-primary" /> |
            @Html.ActionLink("Atrás", "Index", null, new { @class = "btn btn-primary" })
        </div>
    }
</div>

Web/Views/Usuario/Details.cshtml
@model Infraestructure.Models.Usuario

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<h2>Detalles</h2>

<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ubicacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ubicacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Correo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Correo)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>

        <dd>
           @if (Model.Tipo == 0)
           {
               <span> Sin Rol</span>
           }
           else if (Model.Tipo == 1)
           {
               <span>Administrador</span>
           }
           else
           {
               <span>
                   Encargado
               </span>
           }
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Atrás", "Index", null, new { @class = "btn btn-primary" })
</p>

Web/Views/Usuario/Edit.cshtml
@model Infraestructure.Models.Usuario

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<h2>Cambiar tipo</h2>


@using (Html.BeginForm("UpdateUsuario", "Usuario", FormMethod.Post))
{
@Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Usuario</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ubicacion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ubicacion, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.Ubicacion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Correo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
        </div>
    </div>

    <br/>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Dar acceso" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<br/>
<div>
    @Html.ActionLink("Atrás", "Index",null, new { @class = "btn btn-primary"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web/Views/Usuario/Index.cshtml
@model IEnumerable<Infraestructure.Models.Usuario>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<h2>Usuarios</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ubicacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Correo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tipo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ubicacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Correo)
            </td>
            
            <td>
                @if (item.Tipo == 0)
                {
                    <span class="badge bg-danger">
                        Sin Rol
                    </span>
                }
                else if (item.Tipo == 1)
                {
                    <span class="badge bg-success">
                        Administrador
                    </span>
                }
                else
                {
                    <span class="badge bg-primary">
                        Encargado
                    </span>
                }

            </td>
            <td>
                @if (item.Tipo == 0)
                {
                    @Html.ActionLink("Dar acceso", "Edit", new { id = item.Id}, new {@class = "btn btn-primary" }) <span>|</span>
                    @Html.ActionLink("Detalles", "Details", new { id = item.Id }, new { @class = "btn btn-secondary" }) <span>|</span>
                    @Html.ActionLink("Eliminar", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                }
                else if (item.Tipo == 1)
                {
                    @Html.ActionLink("Detalles", "Details", new { id = item.Id }, new { @class = "btn btn-primary" })
                }
                else if (item.Tipo == 2)
                {
                    @Html.ActionLink("Suspender cuenta", "Suspender", new { id = item.Id }, new { @class = "btn btn-primary" }) <span>|</span>
                    @Html.ActionLink("Detalles", "Details", new { id = item.Id }, new { @class = "btn btn-secondary" }) <span>|</span>
                    @Html.ActionLink("Eliminar", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                }
            </td>
        </tr>
    }

</table>

Web/Views/Usuario/Suspender.cshtml
@model Infraestructure.Models.Usuario

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<h2>Cambiar tipo</h2>


@using (Html.BeginForm("SuspenderUsuario", "Usuario", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Usuario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ubicacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ubicacion, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Ubicacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Correo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
            </div>
        </div>

        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Suspender" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<br />
<div>
    @Html.ActionLink("Atrás", "Index", null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}