Web/Controllers/BodegaController.cs
using Core.Interfaces;
using Core.Services;
using Infraestructure.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Web.Utils;

namespace Web.Controllers
{
    public class BodegaController : Controller
    {
        // GET: Bodega
        public ActionResult Index()
        {
            IServiceBodega _ServiceBodega = new ServiceBodega();
            IEnumerable<Bodega> bodegas = _ServiceBodega.GetBodegas();
            return View(bodegas);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Save(Bodega bodega)
        {
            IServiceBodega _ServiceBodega = new ServiceBodega();

            try
            {
                Bodega oBodega = _ServiceBodega.Save(bodega);
                return RedirectToAction("Index");
            }
            catch 
            {
                Utils.Utils.ValidateErrors(this);
                return View("Create",bodega);

            }
        }

        public ActionResult Edit(int? id)
        {
            IServiceBodega _ServiceBodega = new ServiceBodega();
            Bodega bodega;
            try
            {
                if(id == null)
                {
                    return RedirectToAction("Index");
                }

                bodega = _ServiceBodega.GetBodegaById(id.Value);
                
                if(bodega == null)
                {
                    return RedirectToAction("Index");
                }

            }
            catch(Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                return RedirectToAction("Index");
            }
            return View(bodega);

        }

        public ActionResult Details(int? id)
        {
            IServiceBodega _ServiceBodega = new ServiceBodega();
            Bodega bodega;
            try
            {
                if (id == null)
                {
                    return RedirectToAction("Index");
                }

                bodega = _ServiceBodega.GetBodegaById(id.Value);

                if (bodega == null)
                {
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                return RedirectToAction("Index");
            }
            return View(bodega);

        }

        public ActionResult Delete(int? id)
        {
            IServiceBodega _ServiceBodega = new ServiceBodega();
            Bodega bodega;
            try
            {
                if (id == null)
                {
                    return RedirectToAction("Index");
                }

                bodega = _ServiceBodega.GetBodegaById(id.Value);

                if (bodega == null)
                {
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                return RedirectToAction("Index");
            }
            return View(bodega);

        }

        [HttpPost]
        public ActionResult DeleteBodega(Bodega bodega)
        {
            IServiceProducto _ServiceProducto = new ServiceProducto();
            IServiceBodega _ServiceBodega = new ServiceBodega();
            IEnumerable<Producto> productos = null;

            try
            {
                productos = _ServiceProducto.GetBodegaProductoById(bodega.Id);
                
                if(productos.Count() >= 0)
                {
                    return ViewBag.NotificationMessage = SweetAlerts.Mensaje("Error", "No puede eliminar una bodega con productos ", SweetAlerts.SweetAlertMessageType.error);
                }
                else
                {
                    _ServiceBodega.DeleteBodega(bodega.Id);
                }
                return RedirectToAction("Index");
            }
            catch 
            {

                Utils.Utils.ValidateErrors(this);
                return View("Delete", _ServiceBodega.GetBodegaById(bodega.Id));
            }
        }

    }

}

Web/Controllers/ReporteController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Core.Services;
using Infraestructure.Models;
using iText.IO.Font.Constants;
using iText.Kernel.Colors;
using iText.Kernel.Font;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;
using System.IO;
using System.Reflection;
using Core.Interfaces;
using iText.Kernel.Geom;
using System.Linq;

namespace Web.Controllers
{
    public class ReporteController : Controller
    {
        // GET: Reporte
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ReportesSalidas()
        {
            return View();
        }

        public ActionResult CreatePdfEntradas(DateTime? date1, DateTime? date2)
        {
            //Ejemplos IText7 https://kb.itextpdf.com/home/it7kb/examples
            IEnumerable<Movimientos> lista = null;
            try
            {
                // Extraer informacion
                IServiceMovimientos _ServiceMovimientos = new ServiceMovimientos();

                if (date1 != null && date2 != null)
                {
                    lista = _ServiceMovimientos.GetMovimientosEntradaFechas(date1.Value, date2.Value);
                }
                else if (date1 != null && date2 == null)
                {
                    lista = _ServiceMovimientos.GetMovimientosEntradaFechas(date1.Value, null);
                }

                // Crear stream para almacenar en memoria el reporte 
                MemoryStream ms = new MemoryStream();
                //Initialize writer
                PdfWriter writer = new PdfWriter(ms);

                //Initialize document
                PdfDocument pdfDoc = new PdfDocument(writer);
                Document doc = new Document(pdfDoc);

                Paragraph header = new Paragraph("Movimientos de entrada por fecha")
                                   .SetFont(PdfFontFactory.CreateFont(StandardFonts.HELVETICA))
                                   .SetFontSize(14)
                                   .SetFontColor(ColorConstants.BLUE);
                doc.Add(header);


                // Crear tabla con 5 columnas 
                Table table = new Table(9, true);


                // los Encabezados
                table.AddHeaderCell("Nombre de Producto");
                table.AddHeaderCell("Comentario");
                table.AddHeaderCell("Cantidad");
                table.AddHeaderCell("Precio");
                table.AddHeaderCell("Tipo de movimiento");
                table.AddHeaderCell("Proveedor");
                table.AddHeaderCell("Nombre de usuario");
                table.AddHeaderCell("Creado");
                table.AddHeaderCell("Total");


                foreach (var item in lista)
                {

                    List proveedor = new List();
                    // Agregar datos a las celdas
                    table.AddCell(new Paragraph(item.Producto.Nombre));
                    table.AddCell(new Paragraph(item.Comentario));
                    table.AddCell(new Paragraph(item.Cantidad.ToString()));
                    table.AddCell(new Paragraph(item.Producto.Precio.ToString()));
                    table.AddCell(new Paragraph(item.TipoMovimiento.Tipo));

                    foreach (var p in item.Producto.Proveedor)
                    {
                        proveedor.Add(p.Nombre);
                    }
                    table.AddCell(proveedor);

                    table.AddCell(new Paragraph(item.Usuario.Nombre));
                    table.AddCell(new Paragraph(item.Creado.ToString()));
                    table.AddCell(new Paragraph(item.Total.ToString()));
                    proveedor = null;


                }
                doc.Add(table);



                // Colocar número de páginas
                int numberOfPages = pdfDoc.GetNumberOfPages();
                for (int i = 1; i <= numberOfPages; i++)
                {

                    // Write aligned text to the specified by parameters point
                    doc.ShowTextAligned(new Paragraph(String.Format("pag {0} of {1}", i, numberOfPages)),
                            559, 826, i, TextAlignment.RIGHT, VerticalAlignment.TOP, 0);
                }


                //Close document
                doc.Close();

                // Retorna un File
                return File(ms.ToArray(), "application/pdf", "reporte-entradas.pdf");


            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }

        }

        public ActionResult CreatePdfSalidas(DateTime? date1, DateTime? date2)
        {
            //Ejemplos IText7 https://kb.itextpdf.com/home/it7kb/examples
            IEnumerable<Movimientos> lista = null;
            try
            {
                // Extraer informacion
                IServiceMovimientos _ServiceMovimientos = new ServiceMovimientos();


                if (date1 != null && date2 != null)
                {
                    lista = _ServiceMovimientos.GetMovimientosSalidasFechas(date1, date2);
                }
                else if (date1 != null && date2 == null)
                {
                    lista = _ServiceMovimientos.GetMovimientosSalidasFechas(date1, null);
                }

                // Crear stream para almacenar en memoria el reporte 
                MemoryStream ms = new MemoryStream();
                //Initialize writer
                PdfWriter writer = new PdfWriter(ms);

                //Initialize document
                PdfDocument pdfDoc = new PdfDocument(writer);
                Document doc = new Document(pdfDoc);

                Paragraph header = new Paragraph("Movimientos de salida por fecha")
                                   .SetFont(PdfFontFactory.CreateFont(StandardFonts.HELVETICA))
                                   .SetFontSize(14)
                                   .SetFontColor(ColorConstants.BLUE);
                doc.Add(header);


                // Crear tabla con 5 columnas 
                Table table = new Table(8, true);


                // los Encabezados
                table.AddHeaderCell("Nombre de Producto");
                table.AddHeaderCell("Comentario");
                table.AddHeaderCell("Cantidad");
                table.AddHeaderCell("Precio");
                table.AddHeaderCell("Tipo de movimiento");
                table.AddHeaderCell("Proveedor");
                table.AddHeaderCell("Nombre de usuario");
                table.AddHeaderCell("Creado");
                table.AddHeaderCell("Total");


                foreach (var item in lista)
                {

                    List proveedor = new List();
                    // Agregar datos a las celdas
                    table.AddCell(new Paragraph(item.Producto.Nombre));
                    table.AddCell(new Paragraph(item.Comentario));
                    table.AddCell(new Paragraph(item.Cantidad.ToString()));
                    table.AddCell(new Paragraph(item.Producto.Precio.ToString()));
                    table.AddCell(new Paragraph(item.TipoMovimiento.Tipo));

                    foreach (var p in item.Producto.Proveedor)
                    {
                        proveedor.Add(p.Nombre);
                    }
                    table.AddCell(proveedor);

                    table.AddCell(new Paragraph(item.Usuario.Nombre));
                    table.AddCell(new Paragraph(item.Creado.ToString()));
                    table.AddCell(new Paragraph(item.Total.ToString()));
                    proveedor = null;


                }
                doc.Add(table);



                // Colocar número de páginas
                int numberOfPages = pdfDoc.GetNumberOfPages();
                for (int i = 1; i <= numberOfPages; i++)
                {

                    // Write aligned text to the specified by parameters point
                    doc.ShowTextAligned(new Paragraph(String.Format("pag {0} of {1}", i, numberOfPages)),
                            559, 826, i, TextAlignment.RIGHT, VerticalAlignment.TOP, 0);
                }


                //Close document
                doc.Close();
                // Retorna un File
                return File(ms.ToArray(), "application/pdf", "reporte-salidas.pdf");

            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }

        }

        public PartialViewResult ReportesEntradasPartial(DateTime? date1,DateTime? date2)
        {
            IEnumerable<Movimientos> movimientos = null;
            IServiceMovimientos _ServiceMovimientos = new ServiceMovimientos();
            ViewBag.Date1 = date1;
            ViewBag.Date2 = date2;



            if (date1 != null  && date2 != null)
            {
                movimientos = _ServiceMovimientos.GetMovimientosEntradaFechas(date1.Value,date2.Value);
            }
            else if (date1 != null && date2 == null)
            {
                movimientos = _ServiceMovimientos.GetMovimientosEntradaFechas(date1.Value,null);
            }
            else
            {
                movimientos = null;
            }


            return PartialView("_PartialViewReportesEntrada", movimientos);

        }

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles",required:false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Web/Views/Shared/_LayoutMaster.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - Panel</title>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    @{
        string nombre = "";
        string email = "Perfil";
        Infraestructure.Models.Usuario oUsuario;

        if (Session["User"] != null)
        {
            oUsuario = (Infraestructure.Models.Usuario)Session["User"];

            if (oUsuario != null)
            {
                nombre = $"{oUsuario.Nombre}{oUsuario.Apellido}";
                email = oUsuario.Correo;
            }
        }
    }

    <style>
        .color {
            background-color: #3a5b63;
        }

        .btn-primary,
        .btn-primary:hover,
        .btn-primary:active,
        .btn-primary:visited,
        .btn-primary:focus {
            background-color: #80bbd2;
            border-color: #80bbd2;
        }

        .btn-danger,
        .btn-danger:hover,
        .btn-danger:active,
        .btn-danger:visited,
        .btn-danger:focus {
            background-color: #e84848;
            border-color: #e84848;
        }


    </style>

  


    @if (Session["User"] != null)
    {
        <div class="d-flex" id="wrapper">
            <!-- Sidebar-->
            <div class="border-end" id="sidebar-wrapper" style="background-color: #3a5b63;">
                <div class="sidebar-heading border-bottom text-light" style="background-color: #3a5b63;">Neye Store</div>
                <div class="list-group list-group-flush">
                    @{
                        oUsuario = (Infraestructure.Models.Usuario)Session["User"];

                        if (oUsuario.Tipo == 1)
                        {
                            @Html.ActionLink("Panel de Control", "Index", "Home", null, new { @class = "list-group-item list-group-item-action list-group-item-light p-3 color text-light" })
                            @Html.ActionLink("Productos", "Index", "Producto", null, new { @class = "list-group-item list-group-item-action list-group-item-light p-3 color text-light" })
                            @Html.ActionLink("Usuarios", "Index", "Usuario", null, new { @class = "list-group-item list-group-item-action list-group-item-light p-3 color text-light" })
                            @Html.ActionLink("Proveedores", "Index", "Proveedor", null, new { @class = "list-group-item list-group-item-action list-group-item-light p-3 color text-light" })
                            @Html.ActionLink("Movimientos", "Index", "Movimiento", null, new { @class = "list-group-item list-group-item-action list-group-item-light p-3 color text-light" })
                            @Html.ActionLink("Categorías", "Index", "Categoria", null, new { @class = "list-group-item list-group-item-action list-group-item-light p-3 color text-light" })
                            @Html.ActionLink("Tipo Movimientos", "Index", "TipoMovimiento", null, new { @class = "list-group-item list-group-item-action list-group-item-light p-3 color text-light" })
                            @Html.ActionLink("Bodegas", "Index", "Bodega", null, new { @class = "list-group-item list-group-item-action list-group-item-light p-3 color text-light text-light" })
                            @Html.ActionLink("Contactos", "Index", "Contacto", null, new { @class = "list-group-item list-group-item-action list-group-item-light p-3 color text-light text-light" })
                            @Html.ActionLink("Reportes", "Index", "Reporte", null, new { @class = "list-group-item list-group-item-action list-group-item-light p-3 color text-light" })
                        }
                        else if (oUsuario.Tipo == 2)
                        {
                            @Html.ActionLink("Panel de Control", "Index", "Home", null, new { @class = "list-group-item list-group-item-action list-group-item-light p-3 text-light color" })
                            @Html.ActionLink("Productos", "Index", "Producto", null, new { @class = "list-group-item list-group-item-action list-group-item-light p-3 text-light color" })
                            @Html.ActionLink("Proveedores", "Index", "Proveedor", null, new { @class = "list-group-item list-group-item-action list-group-item-light p-3 text-light color" })
                            @Html.ActionLink("Movimientos", "Index", "Movimiento", null, new { @class = "list-group-item list-group-item-action list-group-item-light p-3 text-light color" })
                            @Html.ActionLink("Categorías", "Index", "Categoria", null, new { @class = "list-group-item list-group-item-action list-group-item-light p-3 text-light color" })
                            @Html.ActionLink("Tipo Movimientos", "Index", "TipoMovimiento", null, new { @class = "list-group-item list-group-item-action list-group-item-light p-3 text-light color" })
                            @Html.ActionLink("Bodegas", "Index", "Bodega", null, new { @class = "list-group-item list-group-item-action list-group-item-light p-3 text-light color" })
                            @Html.ActionLink("Contactos", "Index", "Contacto", null, new { @class = "list-group-item list-group-item-action list-group-item-light p-3 text-light color" })
                            @Html.ActionLink("Reportes", "Index", "Reporte", null, new { @class = "list-group-item list-group-item-action list-group-item-light p-3 text-light color" })
                        }
                        else
                        {
                            Response.Redirect("~/Login/NoAutorizado");
                        }
                    }

                </div>
            </div>
            <!-- Page content wrapper-->
            <div>
                <!-- Top navigation-->
                <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #84acb6;">
                    <div class="container-fluid">
                        <button class="btn btn-primary" id="sidebarToggle">
                            <i class="fas fa-bars"></i>
                        </button>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Bienvenido @email</a>
                                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                        @Html.ActionLink("Cerrar Sesión", "Salir", "Login", null, new { @class = "dropdown-item" })
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <!-- Page content-->

                <div class="container" style="background-color: #e4e8e8; ">
                    <div class="row justify-content-center justify-content-md-start" style="background-color: #e4e8e8;">
                        @RenderBody()
                    </div>
                </div>



            </div>
        </div>

    }
    else
    {
        Response.Redirect("~/Login/Index");
    }




    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/js")
    @Scripts.Render("~/bundles/sweetalert")
    @Scripts.Render("~/bundles/jqueryajax")
    @RenderSection("scripts", required: false)
    @if (ViewBag.NotificationMessage != null)
    {
        <script>
            @Html.Raw(ViewBag.NotificationMessage)
        </script>
    }

</body>
</html>