Web/Controllers/CategoriaController.cs
using Core.Interfaces;
using Core.Services;
using Infraestructure.Interfaces;
using Infraestructure.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Web.Utils;

namespace Web.Controllers
{
    public class CategoriaController : Controller
    {
        // GET: Categoria
        public ActionResult Index()
        {
            IServiceCategoria _ServiceCategoria = new ServiceCategoria();
            IEnumerable<Categoria> categorias = _ServiceCategoria.GetCategorias();

            return View(categorias);
        }

        public ActionResult Details(int? id)
        {
            IServiceCategoria _ServiceCategoria = new ServiceCategoria();
            Categoria categoria;
            try
            {
                if (id == null)
                {
                    return RedirectToAction("Index");
                }

                categoria = _ServiceCategoria.GetCategoriaById(id.Value);

                if (categoria == null)
                {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                return RedirectToAction("Index");
            }
            return View(categoria);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Save(Categoria categoria)
        {
            IServiceCategoria _ServiceCategoria = new ServiceCategoria();

            try
            {
                Categoria oCategoria = _ServiceCategoria.Save(categoria);

                return RedirectToAction("Index");
            }
            catch
            {
                Utils.Utils.ValidateErrors(this);
                return View("Create", categoria);
            }

        }

        public ActionResult Edit(int? id)
        {
            IServiceCategoria _ServiceCategoria = new ServiceCategoria();
            Categoria categoria;
            try
            {
                if (id == null)
                {
                    return RedirectToAction("Index");
                }

                categoria = _ServiceCategoria.GetCategoriaById(id.Value);

                if (categoria == null)
                {
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                return RedirectToAction("Index");
            }

            return View(categoria);
        }

        public ActionResult Delete(int? id)
        {
            IServiceCategoria _ServiceCategoria = new ServiceCategoria();
            Categoria categoria;
            try
            {
                if (id == null)
                {
                    return RedirectToAction("Index");
                }

                categoria = _ServiceCategoria.GetCategoriaById(id.Value);

                if (categoria == null)
                {
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                return RedirectToAction("Index");
            }

            return View(categoria);
        }

        [HttpPost]
        public ActionResult DeleteCategoria(Categoria categoria)
        {
            IServiceProducto _ServiceProducto = new ServiceProducto();
            IServiceCategoria _ServiceCategoria = new ServiceCategoria();

            Producto producto;

            try
            {
                producto = _ServiceProducto.GetCategoriaProductoById(categoria.Id);

                if (producto == null)
                {
                    _ServiceCategoria.DeleteCategoria(categoria.Id);
                }
                else
                {
                    return ViewBag.NotificationMessage = SweetAlerts.Mensaje("Error", "No puede eliminar una categoria con productos ", SweetAlerts.SweetAlertMessageType.error);
                }
            }
            catch
            {

                Utils.Utils.ValidateErrors(this);
                return View("Delete", _ServiceCategoria.GetCategoriaById(categoria.Id));
            }
            return RedirectToAction("Index");
        }
    }
}

Web/Views/Categoria/Create.cshtml
@model Infraestructure.Models.Categoria

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<h2>Crear</h2>


@using (Html.BeginForm("Save","Categoria",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Categoria</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Detalle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Detalle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Detalle, "", new { @class = "text-danger" })
            </div>
        </div>
       
        <br/>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </div>
        <br/>
    </div>
}

<div>
    @Html.ActionLink("Atrás", "Index",null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web/Views/Categoria/Delete.cshtml
@model Infraestructure.Models.Categoria

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}



<h3>Quieres eliminarlo?</h3>
<div>
    <h4>Categoría</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Detalle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Detalle)
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteCategoria", "Categoria", new { Id = Model.Id, FormMethod.Post }))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-primary" /> |
            @Html.ActionLink("Atrás", "Index", null, new { @class = "btn btn-primary" })
        </div>
    }
</div>
@section Scripts {
    @Scripts.Render("~/bundles/sweetalert")
}

Web/Views/Categoria/Details.cshtml
@model Infraestructure.Models.Categoria

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<h2>Detalles</h2>

<div>
    <h4>Categoría</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Detalle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Detalle)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary" }) |
    @Html.ActionLink("Atrás", "Index", null, new { @class = "btn btn-primary" })
</p>

Web/Views/Categoria/Edit.cshtml
@model Infraestructure.Models.Categoria

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<h2>Editar</h2>


@using (Html.BeginForm("Save", "Categoria", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Categoria</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Detalle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Detalle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Detalle, "", new { @class = "text-danger" })
            </div>
        </div>
        <br/>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </div>
        <br/>
    </div>
}

<div>
    @Html.ActionLink("Atrás", "Index", null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web/Views/Categoria/Index.cshtml
@model IEnumerable<Infraestructure.Models.Categoria>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<h2>Categorías</h2>



<div class="d-grid gap-2 d-md-block">
    <a href="@Url.Action("Create","Categoria")" class="btn btn-primary">Crear nuevo categoría</a>
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Detalle)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Detalle)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Detalle", "Details", new { id = item.Id }, new { @class = "btn btn-secondary" }) |
                @Html.ActionLink("Eliminar", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>